# Generated by Django 4.1.7 on 2023-08-16 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_remove_post_url_post_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='total_views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
